version : '3'
services:
  mysql_master:
    image: leeyunhyeong/master
    user: root
    build:
      context: ./master
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.11
    container_name: my8_master
    restart: always

  mysql_slave:
    image: leeyunhyeong/slave
    user: root
    build:
      context: ./slave
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 3307:3306
    networks:
      dock_net:
        ipv4_address: 172.16.0.12
    container_name: my8_slave
    restart: always

networks:
  dock_net:
networks:
  dock_net:
    driver: bridge
    ipam:
     config:
        - subnet: 172.16.0.0/16
